### ISSUE TITLE
Create CI and deployment build to Heroku using Travis

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#1]
https://docs.travis-ci.com/user/deployment/heroku

**Comment by MarkAPhillips** [comment]
Chris - 
Can you create an Organisation in GitHub and add me as a member - can you then add this repo to that organisation - this will allow me to access it via Travis to set up the CI Build I am hoping as cannot see another way of doing it presently. - thanks

**Comment by y0rk1e** [comment]
An organisation is priced at $9 (£6.12) per user per month. Is this a requirement? If so I don't mind paying for it. Let me know and I can set it up when I am at home.

**Comment by MarkAPhillips** [comment]
Hi Chris you should not have to pay for this.Is the repo you created Public or private?Another alternative is to login into travis yourself and switch the build on for the repo.But I am not sure how I can access to it ? Try this and I'll take a look.Mark
Date: Wed, 22 Jun 2016 05:18:22 -0700

**Comment by y0rk1e** [comment]
I logged in on Travis and I turned it on for the project on GitHub. I am not sure if you will see it. Let me know if this works.

**Comment by MarkAPhillips** [comment]
Works as expected just to configure it correctly

**Comment by y0rk1e** [comment]
Ok, how do I do this or are you able to see it in Travis now?

When I turned it on there was some option to add a config file to the GIT repository or at the very least not run a build unless a config file was present.

**Comment by MarkAPhillips** [comment]
Am in the process of looking at this I may need access to the travis build but dont worry about this in the meantime as need to set a up a simple Node Express server to be able to run the application in Heroku

**Comment by MarkAPhillips** [comment]
Completed
