### ISSUE TITLE
Business clarification:  Terms of Use link on register view

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#10]
Required ?
Details - implementation requirements

**Comment by y0rk1e** [comment]
Yes; I believe this will be required. The text should probably read something like:

"I have read and accepted the terms and conditions" where 'terms and conditions' is a link to the terms and conditions page.

**Comment by MarkAPhillips** [comment]
OK - will close this and add Terms and Conditions page to the backlog.
