### ISSUE TITLE
Does not accept email in the username field when registering via Web API

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#13]
Request payload: {"firstName":"Mark","lastName":"Phillips","email":"xx-xxxxx@outlook.com","password":"qwerty1Q£","confirmPassword":"qwerty1Q£","acceptTerms":true}

Error :
{"message":"The request is invalid.","modelState":{"":["User name xx-xxxxx@outlook.com is invalid, can only contain letters or digits."]}}

Still getting this error message from the UI.

**Comment by y0rk1e** [comment]
This has been fixed. Latest version of the API has been published to Azure.
