### ISSUE TITLE
Add Rest Web API call to check if a username/email exists

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#16]
Used to validate an email address on the registration form.

`
POST /api/accounts/exists
Content-Type: application/json
{
          email : test@test.co.uk
}
`

Response 

`
HTTP/1.1 200 OK 
Content-Type: application/json
{
     exists: true | false
}
`

**Comment by y0rk1e** [comment]
I can add this; however how do we secure it? To ensure that people don't use this endpoint to find usernames in the system?

**Comment by MarkAPhillips** [comment]
OK - we can park this - there is an minor impact on security but we could whitelist the urls referencing it  - CORS takes care of browser access - we could also add basic authentication to the header on the login/account APIs that don't require the token.  This can be reviewed at a later date.
