### ISSUE TITLE
Security headers addition and removal from MVC Web API requests

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#17]
Remove X-Powered-By:ASP.NET

`
 <system.web>
    <httpRuntime  enableVersionHeader="false" />
  </system.web>
`

Remove Server:Microsoft-IIS/8.0 and add nosniff
see https://msdn.microsoft.com/en-us/library/gg622941(v=vs.85).aspx

require Url rewrite module which may be required on Azure - there maybe a newer way of doing this now so worth doing a quick bit of research

`  
<system.webServer>
 <rewrite>
      <outboundRules>
        <rule name="Remove RESPONSE_Server">
          <match serverVariable="RESPONSE_Server" pattern=".+" />
          <action type="Rewrite" value="Chrodie" />
        </rule>
      </outboundRules>
    </rewrite>
    <httpProtocol>
      <customHeaders>
        <clear />
        <add name="X-Content-Type-Options" value="nosniff" />
      </customHeaders>
    </httpProtocol>
</system.webServer>
`

**Comment by y0rk1e** [comment]
X-Powered-By:ASP.NET **- removed**
Server:Microsoft-IIS/8.0 **- removed**
X-Content-Type-Options = nosniff **- added**
