### ISSUE TITLE
Return given_name and family_name in claims token

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#47]
https://azure.microsoft.com/en-gb/documentation/articles/active-directory-token-and-claims/

Would it be possible to return this information as part of the claims it can displayed when the user logs in ?

There is "unique_name" but assume this is the username or email.

**Comment by MarkAPhillips** [comment]
@y0rk1e  can we look at implementing this on the application early this week - thanks

**Comment by y0rk1e** [comment]
I have my laptop with me at work. I'll take care of this at lunch time or on the train home

**Comment by y0rk1e** [comment]
<img width="605" alt="addingnamestojwttoken" src="https://cloud.githubusercontent.com/assets/13914641/17479315/cf4847f6-5d69-11e6-809c-b0707558edee.png">

I have added the FirstName and LastName fields from the user object to the JWT. This has not been published to Azure as I haven't configured publishing from my laptop. I will get that resolved tonight.

**Comment by y0rk1e** [comment]
Just realised that you would probably prefer the names to be lower cased first character. I will get this changed before publishing to Azure.

**Comment by y0rk1e** [comment]
In fact, looking at it now, which would you prefer?

given_name & family_name

or

first_name & surname

**Comment by MarkAPhillips** [comment]
I assume it does not matter - the given_name & family_name were part of the standard - are first_name & surname custom fields you have created or part of a standard as would rather stick to standards if possible - thanks

**Comment by y0rk1e** [comment]
![addingnamestojwttoken updated](https://cloud.githubusercontent.com/assets/13914641/17490100/22334d4c-5d99-11e6-9900-537e54c22b37.png)


This is now live
