### ISSUE TITLE
Add client code for  an user to register and allow for registration

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#5]
http://chrodie.azurewebsites.net/api/accounts/user

{
    "email": "**@**.com",
    "password": "InitialPassword!",
    "confirmPassword": "InitialPassword!",
    "firstName": "Test",
    "lastName": "User",
    "acceptTerms": "true"
  }

**Comment by MarkAPhillips** [comment]
Complete, an user can register successfully.

**Comment by y0rk1e** [comment]
Great!! I'll try it out when I get home.
