### ISSUE TITLE
Review Balsamiq Mock ups

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#54]
Review Balsamiq mock ups and break into user stories for development

**Comment by MarkAPhillips** [comment]
see http://adazzle.github.io/react-data-grid/examples.html#/editable

I think this component in react might help with data entry on the view to give an Excel like view.

**Comment by y0rk1e** [comment]
The main concern here is speed of data entry which is where similar systems fail when compared with desktop software. There are columns which will require drop down boxes and should support an auto complete feature allowing the user to quickly find and select using tab the entry they want.

Other cells will auto calculate base on previous cell entries however they will still allow the user to change their contents.

Data validation is also a requirement to ensure the format of certain cells is adhered to eg. Date, currency, string lengths, etc.

I can have a prospective user test a mock table if you wish to create one to see if this component is a possibility

**Comment by MarkAPhillips** [comment]
Ok will create a simple demo on the main page for review - to be honest - not until you start using these components can you have an idea as to how well they will perform and if they suit all business requirements.
