### ISSUE TITLE
Create Web API endpoint for Customers Data

### ISSUE THREAD

**Issue by MarkAPhillips** [y0rk1e/Chrodie.WebApp#61]
Chris - can you advise what the endpoint for this will be ?
And what data will be returned - initially can be id, name

I have used this in the past to create random data sets in case you are not aware:

https://www.mockaroo.com/

**Comment by y0rk1e** [comment]
I have never used mockaroo before. It looks really good, I am in the process of updating the authorisation API to issue tokens the business API can consume.

I will send you the initial model specs for customers tomorrow, if I can I'll generate some mock data too.

**Comment by y0rk1e** [comment]
Hi Mark,

Sorry for the delay. here is the expected data model for the customers:

int Id
string Name
string AddressLine1
string AddressLine2
string Town
string County
string PostCode
int DefaultNominal
string ContactName
string ContactNumber
string Website
string Email1
string Email2
double DefaultVat

As for what will be displayed on in the customers listing. This has not been 100% finalised. I will confirm this with the BA. I suspect it would be something like:

Name, Contact Name, Telephone, Balance

**Comment by MarkAPhillips** [comment]
Chris do you think this will done next week? If you login to the test site you can now see a dummy customer view - this is currently limited to 20 records - I am going to review a table/grid so I don't have to create custom sorting and paging - I will probably use the datagrid I mentioned for read only data also.

**Comment by y0rk1e** [comment]
I'll get this working this weekend

**Comment by y0rk1e** [comment]
I will push the first revision of the business API to azure tonight. The code is mostly complete just a matter of creating the azure resources and setting up then nhibernate SQL server.

Took slightly longer that I expected. I wanted to follow the unit of work and repository patterns.
