### ISSUE TITLE
Updating authentication to support multiple audiences

### ISSUE THREAD

**Issue by y0rk1e** [y0rk1e/Chrodie.WebApp#65]
Hi Mark,

If I push the next set of changes to the authentication API it will require a client_Id to be passed as one of the parameters. The client_Id effectively is for the backend to know for which audience (Api) it should generate a token for. The generation of the token then uses a secret key in the creation of the token. These keys are different for each audience if we are to create more than one API in this system.

This does have a little but of a design consideration. It would mean that in order to login and update your password you would get a Token which is valid to communicate with the Authentication API but that token is not valid to communicate with the BusinessAPI as the secret key would be different.

Obviously at this point we only have the Authentication API and a single Audience (BusinessAPI) so we could use the same secret for both and if a user is authenticated with one they can communicate with the other using the same token depending on claims etc.

Let me know what works best for you on the client side. I don't want to push the changes in their current form if it does not fit well.

Cheers

**Comment by MarkAPhillips** [comment]
For simplicity sake initially can we go with using the same secret for both - moving forward I assume the Authentication API would be the main API that would provide various keys for the other APIs after a user has logged in - do you have any links in relation to security model you are intending to follow? so I can take a look - wouldn't the concept of a master key define what APIs an User has access to suffice - i.e possibly have a proxy which handles all requests to the various APIs  which also contains authorisation rules

**Comment by y0rk1e** [comment]
I am using OWIN middleware for authorisation. the workflow I have implemented is similar to how Facebook or Google would allow you to use their authentication servers for your own web services. They allow you to grant Google/FB permission using a client_id to generate tokens on your behalf with a given key. Your service can then consume these tokens as they have been created by a trusted authorisation server using a secret only you and Google/FB share.

Have a look at OAuth 2.0 flow charts. It has the same workflow.

For the time being I will use the same key for both APIs for simplicity. We can review this at a later date.

**Comment by y0rk1e** [comment]
Implemented - now live in Azure.
Ensure you pass the client_Id as part of the request.

![image](https://cloud.githubusercontent.com/assets/13914641/17681584/8694e502-633e-11e6-8753-b3ca0d8f1ccc.png)
