### ISSUE TITLE
Heroku - Is it working?

### ISSUE THREAD

**Issue by y0rk1e** [y0rk1e/Chrodie.WebApp#67]
I attempted to login on the Heroku site; it failed due to CORS issues and https warnings.

Is this expected or should it be working?

**Comment by MarkAPhillips** [comment]
Not sure - I will test the login - today and post any errors - try the http site - not the https site as you will get issues with this.

**Comment by MarkAPhillips** [comment]
Tested and logs in as expected using the http: site with user name chris.....@gmail.com
